## Resumo

- Para ler um arquivo externo, inclua-o aqui no colab e depois execute
```python
df = pd.read_csv("nome_do_arquivo.csv")
```
- Para explorar algumas linhas use
```python
df.head(3)   # Mostra as primeiras linhas
df.tail(2)   # Mostra as últimas linhas
df.sample(5) # Mostra uma amostra aleatória dos dados
```

- Alguns resumos úteis
```python
df.info()     # Mostra resumo das colunas e seus tipos
df.describe() # Mostra um resumo estatístico de colunas numéricas
df.columns    # Mostra os nomes das colunas
```

## Exercício 1

Utilize como base o dataset `dataset-netflix.csv` para este exercício.  

Siga as instruções para responder cada pergunta:

### **Item 0**
Carregue o arquivo correspondente aqui no notebook do colab, leia-o com pandas e salve num dataframe chamado `df`.

Dicas:
- Baixe o arquivo do Drive na sua máquina
- Faça o upload dele aqui no colab
- Leia o arquivo usando `pd.read_csv`

In [433]:
import pandas as pd # importa o pandas e da apelido

df = pd.read_csv('dataset-netflix.csv')#importa o csv e chama de df(dataframe)

### **Item 1**
Crie uma nova coluna que indique a idade do filme/série (ou há quantos anos foi o seu lançamento)

Dicas:
- Investigue o DataFrame para descobrir qual coluna representa o ano de lançamento dos filmes/séries
- Lembre-se como calcular a idade sabendo o "ano de nascimento" (precisamos substrair o ano de nascimento do ano em que estamos)
- Salve o cálculo numa nova coluna. Pode chamá-la de `idade`

In [443]:
df.rename(columns= {
    "show_id": "id",
    "type": "tipo",
    "title": "titulo",
    "director":"direcao",
    "cast": "elenco",
    "country": "país",
    "date_added": "data",
    "release_year": "ano lancamento",
    "rating": "classificacao",
    "duration": "duracao",
    "listed_in": "genero",
    "description": "sinopse"
}, inplace=True,)#renomeando as colunas e aplicando direto no df com inplace

df['data lancamento'] = 2026 - df['ano lancamento']#criando coluna data lancamento

df#chamando o df para conferencia

,id,tipo,titulo,direcao,elenco,país,data,ano lancamento,classificacao,duracao,genero,sinopse,data lancamento
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",6
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",5
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,5
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",5
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",19
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",8
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,17
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",20
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,11

### **Item 2**
Selecione todos os **filmes** e salve o resultado num novo dataframe chamado `filmes`

Dicas:
- A coluna `"type"` informa se a linha corresponde a um filme (`"Movie"`) ou a um seriado (`"TV Show"`)
- Crie um filtro igualando a coluna `"type"` à string `"Movie"`
- Use `df.loc` para aplicar o filtro ao dataframe como um todo
- Não esqueça de salvar o resultado do `df.loc` na variável `filmes`

In [435]:
# df_filmes = df['titulo'].unique() #verificando os tipos unicos dentro da coluna titulo(apenas 2 = Movie / TV Show)

# df['tipo'] == 'Movie'
df_filmes = df.loc[df['tipo'] == 'Movie'] #filtro buscando todos os filmes e adicionando em um novo df_filmes
df_tv_show = df.loc[df['tipo'] =='TV Show']#filtro buscando todos os filmes e adicionando em um novo df_tv_show
df_filmes.head()#chamando para conferir somente os 5 primeiros

,id,tipo,titulo,direcao,elenco,país,data,ano lancamento,classificacao,duracao,genero,sinopse,data lancamento
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",6
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...,5
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...",33
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...,5
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...,5

### **Item 2**
Dentre todos os filmes, filtre aqueles que foram lançados antes de 2000.  
Salve o resultado numa nova variável chamada `filmes_antigos`.

Dicas:
- **Como usaremos apenas filmes, usa a variável `filmes` como dataframe ao invés do `df`**
- A coluna `"release_year"` informa o ano de lançamento do título
- Crie um filtro para buscar anos de lançamento menores que 2000
- Use `filmes.loc` para aplicar o filtro ao dataframe `filmes` como um todo
- Não esqueça de salvar o resultado do `filmes.loc` na variável `filmes_antigos`

In [436]:
# df_filmes['ano lancamento'] < 2000 #parametro do filtro
df_filmes_antigos = df_filmes.loc[df_filmes['ano lancamento'] < 2000]#df recebendo somente os dados do filtro com parametro ano lancamento < 2000

df_filmes_antigos.head()#chamando para conferir somente os 5 primeiros

,id,tipo,titulo,direcao,elenco,país,data,ano lancamento,classificacao,duracao,genero,sinopse,data lancamento
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...",33
22,s23,Movie,Avvai Shanmughi,K.S. Ravikumar,"Kamal Hassan, Meena, Gemini Ganesan, Heera Raj...",NaN,"September 21, 2021",1996,TV-PG,161 min,"Comedies, International Movies",Newly divorced and denied visitation rights wi...,30
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...,28
26,s27,Movie,Minsara Kanavu,Rajiv Menon,"Arvind Swamy, Kajol, Prabhu Deva, Nassar, S.P....",NaN,"September 21, 2021",1997,TV-PG,147 min,"Comedies, International Movies, Music & Musicals",A tangled love triangle ensues when a man fall...,29
41,s42,Movie,Jaws,Steven Spielberg,"Roy Scheider, Robert Shaw, Richard Dreyfuss, L...",United States,"September 16, 2021",1975,PG,124 min,"Action & Adventure, Classic Movies, Dramas",When an insatiable great white shark terrorize...,51

### **Item 3**
Para finalizar, busque apenas os filmes antigos do "Steven Spielberg"

Dicas:
- Como usaremos apenas filmes antigos, use a variável `filmes_antigos` como dataframe
- A coluna `"director"` informa o diretor associado ao título
- Crie um filtro para buscar diretores iguais a `"Steven Spielberg"`
- Use `df.loc` para aplicar o filtro ao dataframe `filmes_antigos` como um todo

In [437]:
# df_filmes_antigos['direcao'] == 'Steven Spielberg'
df_filmes_antigos.loc[df_filmes_antigos['direcao'] == 'Steven Spielberg']#filtro para trazer somente dado especifico da tabela

,id,tipo,titulo,direcao,elenco,país,data,ano lancamento,classificacao,duracao,genero,sinopse,data lancamento
41,s42,Movie,Jaws,Steven Spielberg,"Roy Scheider, Robert Shaw, Richard Dreyfuss, L...",United States,"September 16, 2021",1975,PG,124 min,"Action & Adventure, Classic Movies, Dramas",When an insatiable great white shark terrorize...,51
7071,s7072,Movie,Indiana Jones and the Last Crusade,Steven Spielberg,"Harrison Ford, Sean Connery, Denholm Elliott, ...",United States,"January 1, 2019",1989,PG-13,127 min,"Action & Adventure, Children & Family Movies, ...","Accompanied by his father, Indiana Jones sets ...",37
7072,s7073,Movie,Indiana Jones and the Raiders of the Lost Ark,Steven Spielberg,"Harrison Ford, Karen Allen, Paul Freeman, Rona...",United States,"January 1, 2019",1981,PG,116 min,"Action & Adventure, Children & Family Movies, ...",When Indiana Jones is hired by the government ...,45
7073,s7074,Movie,Indiana Jones and the Temple of Doom,Steven Spielberg,"Harrison Ford, Kate Capshaw, Amrish Puri, Rosh...",United States,"January 1, 2019",1984,PG,119 min,"Action & Adventure, Children & Family Movies, ...","Indiana Jones, his young sidekick and a spoile...",42
7957,s7958,Movie,Schindler's List,Steven Spielberg,"Liam Neeson, Ben Kingsley, Ralph Fiennes, Caro...",United States,"April 1, 2018",1993,R,195 min,"Classic Movies, Dramas",Oskar Schindler becomes an unlikely humanitari...,33

### **Desafio 1**

Quantos filmes (`Movie`) e quantas séries (`TV Show`) há neste dataset?  

Há várias formas de calcular esses números.  
Tente calcular primeiramente usando as ferramentas que você já conhece.  
Depois use `.value_counts()`

In [438]:
len(df_filmes) #soma linhas da tabela ou .shape[0]
# len(df_tv_show) #total de linhas da tabela ou .shape[0]
# df_filmes['id'].count() #ignorando os valores nulos 6131
# df_filmes['id'].size #inclui os nulos na contagem
df_filmes['duracao'].value_counts() # traz os itens e quantas x ele aparece
# df_filmes['duracao'].unique()#conta valores unicos e mostra quais sao na coluna
# df_filmes['id'].nunique() #conta linhas com valores unicos
# (df_filmes['ano lancamento'] < 2000).sum()#contagem condicional

duracao
90 min     152
97 min     146
94 min     146
93 min     146
91 min     144
          ...
228 min      1
18 min       1
205 min      1
201 min      1
191 min      1
Name: count, Length: 205, dtype: int64

### **Desafio 2**

Há alguns filmes que possuem mais de um diretor. Nesses caso o filtro de `==` não funcionará caso você queira buscar os filmes de um diretor em específico.  

Experimente usar o método `.str.contains()` como filtro e compare-o com o uso convencional do `==` para perceber a diferença nos resultados.  
Busque pelos nomes de `Jesse V. Johnson` ou `Akiva Schaffer` como exemplo.

*Dica*: o uso de `.str.contains()` gera erro ao ser usado em uma coluna com valores nulos.  
Use alguma das técnicas que aprendemos para eliminar os nulos antes de aplicar os filtros.
- Elimine os nulos usando `.dropna()`
- Preencha-os com um texto padrão de `"Não definido"` usando `df.fillna()`

In [439]:
# df_filmes.dropna(subset=['direcao']) #Remove linhas onde a coluna direcao está NaN / subset=['direcao'] → aplica o filtro só nessa coluna
# ou
# df_filmes = df_filmes.fillna("nao definido") #Substitui todos os NaN do DataFrame por "nao definido"
# df_filmes['direcao'] = df_filmes['direcao'].fillna("nao definido") #Substitui todos os NaN da coluna especifica do DataFrame por "nao definido"
# df_filmes['direcao'].str.contains("Jesse") #Retorna uma Series booleana (True/False)#Verifica se cada linha da coluna direcao contém "Jesse" Usado como filtro
# df_filmes.loc[df_filmes['direcao'].str.contains("Jesse")] #Verifica se cada linha da coluna direcao contém "Jesse"

df_filmes.loc[
    df_filmes['direcao'].str.contains("Jesse V. Johnson") |
    df_filmes['direcao'].str.contains("Akiva Schaffer", na=False)]#Filtro completo com múltiplas condições#na=False → se for NaN, retorna False (evita erro)

# Case insensitive (boa prática real)
  # padrao = r"Jesse V\. Johnson|Akiva Schaffer"

  # df_filmes.loc[
  #   df_filmes['direcao'].str.contains(padrao, case=False, na=False)]

,id,tipo,titulo,direcao,elenco,país,data,ano lancamento,classificacao,duracao,genero,sinopse,data lancamento
2083,s2084,Movie,The Debt Collector 2,Jesse V. Johnson,"Scott Adkins, Louis Mandylor, Vladimir Kulich,...",United States,"August 31, 2020",2020,TV-MA,97 min,Action & Adventure,French and Sue have two days to collect on thr...,6
3511,s3512,Movie,Avengement,Jesse V. Johnson,"Scott Adkins, Craig Fairbrass, Thomas Turgoose...",United Kingdom,"September 17, 2019",2019,TV-MA,88 min,Action & Adventure,"Betrayed by his loan shark brother, a hardened...",7
3717,s3718,Movie,Triple Threat,"Jesse V. Johnson, Jesse Johnson","Tony Jaa, Iko Uwais, Tiger Chen, Scott Adkins,...","Thailand, China, United States","June 22, 2019",2019,R,96 min,"Action & Adventure, International Movies",A crew of ruthless criminals hired to kill an ...,7
3802,s3803,Movie,The Lonely Island Presents: The Unauthorized B...,"Mike Diva, Akiva Schaffer","Andy Samberg, Akiva Schaffer, Jorma Taccone, H...",NaN,"May 23, 2019",2019,TV-MA,30 min,"Comedies, Music & Musicals, Sports Movies",The Lonely Island spoofs notorious baseball st...,7
4661,s4662,Movie,The Debt Collector,Jesse V. Johnson,"Scott Adkins, Louis Mandylor, Vladimir Kulich,...","United Kingdom, United States","September 3, 2018",2018,TV-MA,96 min,Action & Adventure,A broke martial arts instructor takes a side g...,8
5613,s5614,Movie,"Michael Bolton's Big, Sexy Valentine's Day Spe...","Scott Aukerman, Akiva Schaffer","Michael Bolton, Andy Samberg, Will Forte, Kenn...",United States,"February 7, 2017",2017,TV-MA,54 min,"Comedies, Music & Musicals, Romantic Movies","After Santa tells him he needs 75,000 new babi...",9
7005,s7006,Movie,Hot Rod,Akiva Schaffer,"Andy Samberg, Jorma Taccone, Bill Hader, Danny...",United States,"November 20, 2019",2007,PG-13,88 min,"Comedies, Sports Movies",Andy Samberg stars in this comedy as an accide...,19
7369,s7370,Movie,Mad Money,"Callie Khouri, Jesse V. Johnson","Diane Keaton, Queen Latifah, Katie Holmes, Ted...",United States,"November 1, 2019",2008,PG-13,99 min,Comedies,A woman joins the janitorial staff of the Fede...,18
7946,s7947,Movie,Savage Dog,Jesse V. Johnson,"Scott Adkins, Juju Chan, Marko Zaror, Vladimir...",United States,"November 1, 2017",2017,TV-MA,95 min,"Action & Adventure, Independent Movies",A former professional boxer serving time in a ...,9

### **Desafio 3**

Note que a coluna de `duration` contém a informação de duração de filmes e séries de modo distinto:
- Para filmes o valor é `XXX min`
- Para séries o valor é `YYY Season(s)`

Como faríamos para converter essa coluna em uma coluna numérica que informa a duração em minutos para os filmes?

**Importante**: É mais fácil se manipularmos apenas os filmes, portanto use o dataframe `filmes` neste exemplo.

- Aplique o método `.str.split(expand=True)` na coluna duration e observe o resultado
- Note que duas novas colunas foram criadas, uma com nome `0` e outra com nome `1`
- A informação que queremos está na coluna `0`, então elimine a outra usando `.drop()`
- Renomeie a coluna `0` para `duration_min` usando o método `.rename()` no dataframe
- Descubra quais são os filmes mais curto e mais longo do catálogo

In [ ]:
df_filmes['duracao_min'] = (df_filmes['duracao']#cria a coluna duracao_min e adiciona os parametros
  .str.split(expand=True)#realiza o split de num e string
  .drop(columns=[1])#deleta a coluna
  .rename(columns={0: 'duracao_min'})#renomeia a coluna
)

df_filmes.columns #ver as colunas apos adicionar

# df_filmes['duracao_min'].isna().sum() #trazer quantidade de linhas nan na coluna

In [ ]:
# tranforma linhas vazias para 0 e transforma string em int
df_filmes['duracao_min'] = (df_filmes['duracao_min']
 .fillna(0)   #tranforma NAN em 0
 .astype(int) #converte de string para int
 )

In [442]:
df_filmes.loc[
    df_filmes['duracao_min'] == 0]

# filmes com longa duracao
# df_filmes.loc[
#     df_filmes['duracao_min']
#     .sort_values(ascending=False)
#     .head(5)
#     .index
#             ]
#filmes com curta duracao
# df_filmes.loc[
#     df_filmes[df_filmes['duracao_min']>0]
#     .sort_values(by='duracao_min', ascending=True).head(5)
#     .index
#               ]

,id,tipo,titulo,direcao,elenco,país,data,ano lancamento,classificacao,duracao,genero,sinopse,data lancamento,duracao_min
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi...",9,0
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...,16,0
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...,11,0